### ISSUE TITLE
Tracking Issue: Value References

### ISSUE THREAD

**Issue by kellerkindt** [kellerkindt/asn1rs#50]
ValueReferences are the constants of ASN.1. With this PR constant definitions in ASN.1 are parsed.

  * [ ] Parse and resolve basic Value References (Integers) #49 
  * [ ] Add constant values to rust
  * [ ] Properly parse hex values and other non-integer VRs

PR #49 changes public API and thus is a breaking change in  this regard. ~A version bump to `0.3.0 ` is therefore required by the [semantic versioning guidelines](https://semver.org/)~ No. 4: "Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable."

This resolves #45
